

export const array = [{"category":"Entertainment: Film","type":"multiple","difficulty":"easy","question":"Which animated movie was first to feature a celebrity as a voice actor?","correct_answer":"Aladdin","incorrect_answers":["Toy Story","James and the Giant Peach","The Hunchback of Notre Dame"]},

{"category":"Celebrities","type":"multiple","difficulty":"medium","question":"Paul McCartney has always used his middle name. What is his real first name? ","correct_answer":"James","incorrect_answers":["John","Jack","Justin"]},
{"category":"Art","type":"boolean","difficulty":"medium","question":"Pablo Picasso is one of the founding fathers of &quot;Cubism.&quot;","correct_answer":"True","incorrect_answers":["False"]},
{"category":"Entertainment: Books","type":"multiple","difficulty":"easy","question":"Who was the author of the 1954 novel, &quot;Lord of the Flies&quot;?","correct_answer":"William Golding","incorrect_answers":["Stephen King","F. Scott Fitzgerald","Hunter Fox"]},
{"category":"Entertainment: Video Games","type":"multiple","difficulty":"hard","question":"Which of these characters was considered, but ultimately not included, for Super Smash Bros. Melee?","correct_answer":"James Bond","incorrect_answers":["Diddy Kong","Mega Man","Wave Racer"]},
{"category":"Entertainment: Music","type":"multiple","difficulty":"hard","question":"Which of Michael Jackson&#039;s albums sold the most copies?","correct_answer":"Thriller","incorrect_answers":["Dangerous","Bad","Off the Wall"]},
{"category":"Entertainment: Video Games","type":"multiple","difficulty":"easy","question":"What were the first two blocks in &quot;Minecraft&quot;?","correct_answer":"Grass and Cobblestone","incorrect_answers":["Grass and Stone","Crafting Table and Cobblestone","Cobblestone and Stone"]},
{"category":"Entertainment: Music","type":"multiple","difficulty":"medium","question":"Which album by American rapper Kanye West contained songs such as &quot;Love Lockdown&quot;, &quot;Paranoid&quot; and &quot;Heartless&quot;?","correct_answer":"808s &amp; Heartbreak","incorrect_answers":["Late Registration","The Life of Pablo","Graduation"]},
{"category":"History","type":"multiple","difficulty":"hard","question":"The ancient city of Chich&eacute;n Itz&aacute; was built by which civilization?","correct_answer":"Mayans","incorrect_answers":["Aztecs","Incas","Toltecs"]},
{"category":"Celebrities","type":"multiple","difficulty":"medium","question":"What year was O.J. Simpson aquitted of his murder charges?","correct_answer":"1995","incorrect_answers":["1992","1996","1991"]}]